# 构建 Url
POST http://127.0.0.1:9000/urlBuildJJF7_2Tqm-zh4dbF
Content-Type: application/json

{"host":"pi.anycps.com:8002","id":"ominous-sniffle-g4q77pgx49g7f9664-9000","ssl":false}


### 获取 Url
GET http://127.0.0.1:9000/urlBuildJJF7_2Tqm-zh4dbF
Content-Type: application/json
 



### 获取 Url
GET http://127.0.0.1:9000
Content-Type: application/json